### ISSUE TITLE
the Gui not loading

### ISSUE THREAD

**Issue by T0PGlitch3r** [xiaoxiao921/UnchainedTogether#3]
gui isn't loading on v1.8.0
![Screenshot 2024-07-04 163942](https://github.com/xiaoxiao921/UnchainedTogether/assets/31157485/f103c6b2-4c28-49f7-9aa2-b2d7a2b887fa)

**Comment by xiaoxiao921** [comment]
I tested it and it works fine, you need to go in game and select a character.

**Comment by T0PGlitch3r** [comment]
i see ok yes its working
